### ISSUE TITLE
Invalid paths in used in backtrace.

### ISSUE THREAD

**Issue by Gert-dev** [gwomacks/php-debug#107]
Hello

I've discovered a minor bug that prevents me from properly using the backtrace when a breakpoint is triggered: the paths seem to be absolute, but do not have a leading slash, e.g. I see `home/user/website/main.php` instead of `/home/user/website/main.php`. This causes clicking the filename to open a new empty file instead of the actual file and navigating to the correct line.

Thanks in advance

**Comment by cchamplin** [comment]
This should be resolved in today's release

**Comment by Gert-dev** [comment]
I gave it a whirl today and unfortunately still have the same issue. Is there anything else I can do to debug this and help you fix this?

**Comment by N4M3Z** [comment]
I confirm, that I am having the same issue, the leading `/` is missing in all paths. I guess this is an escaping issue.

**Comment by cchamplin** [comment]
@Gert-dev If you're willing and want to locate the local install of php-debug, there should be a file "helpers.coffee" if you want to replace the very last line of that file

`return remotePath.replace('file:///','')`

with 
`return remotePath.replace('file://','')`

and then reload atom, and tell me if that fixes that issue that would be very helpful!

**Comment by N4M3Z** [comment]
@Gert-dev Yeah, that fixed it for me. Should we also change it on l.80?

**Comment by cchamplin** [comment]
Hopefully fixed in v0.2.2 - Released Today

**Comment by Gert-dev** [comment]
Sorry for the late reply, the solution also solves it for me. I'll try it out again next week and will open the ticket again if the problem persists (otherwise, assume it's fixed ;-).
