### ISSUE TITLE
Working bad since last updates

### ISSUE THREAD

**Issue by jvlobo** [gwomacks/php-debug#294]
Hi there!

Since the last big update (when it requires to install an extra plugin etc) this plugin is not working as well as it did before.

Sometimes it doesn't stop on breakpoints. The PHP Debug panel opens randomly when it's closed. It opens a lot of random panels... in summary. it doesn't work well.

I'm wondering if it is just me or other users are experiencing the same weird behaviour.

Cheers!

**Comment by cchamplin** [comment]
Duplicate of #291 

This should be fixed in the next release (sometime this week). There is a flag that's sent to xdebug but to disable multiple connections but it looks like xdebug is ignoring this in certain situations.

**Comment by cchamplin** [comment]
Should be Fixed in v0.3.5. If not please reopen

**Comment by jvlobo** [comment]
Hey, thanks for the update. I've to 0.3.5 but issues are still there.
For example, it stops on the breakpoint even if I don't have the PHP Debug console open.
It also opens randomly PHP Console when debugging
Cheers!

**Comment by cchamplin** [comment]
@jvlobo Have to unchecked the setting to allow multiple connections?

**Comment by jvlobo** [comment]
Ok, I've unchecked that one.

But I had unchecked the **Continue to listen for debug session even if the debugger windows are all closed** and it stop on breakpoint with the debugger windows closed... 

Thanks!

**Comment by SleepWalker** [comment]
> @jvlobo Have to unchecked the setting to allow multiple connections?

@cchamplin If I uncheck this checkbox, it won't catch any break point at all.

If I leave this setting, it opens many tabs like `PHP Debug(<number>)` and when I try to 'step over' it writes 'Session active: BREAK' and all the navigation buttons are disabled. The only option, that I have in such case — Detach or Stop.

![image](https://user-images.githubusercontent.com/2536916/41155240-dc3243c4-6b25-11e8-9553-13a4c4c86068.png)

**Comment by ciscon** [comment]
As of now if I uncheck that box it may or may not catch the initial breakpoint, but stepping through will break almost immediately as new requests/connections are made throughout the run of that php process so it just gets hung.  If I allow multiple connections, I'm just flooded with new phpdebug/console tabs.  Can we just have it behave as it did before and accept multiple connections and use the same two tabs?

**Comment by cchamplin** [comment]
Unchecking accept multiple connections should result in the same behavior as the prior version (0.2.x) where new connections are rejected if a connection is already active. Can you enable protocol debugging and provide a paste of the output from the atom debug console?

**Comment by ciscon** [comment]
It just seems to be very inconsistent- if I disallow multiple connections, my cli spawned php doesn't hit any breakpoints, I just see a session start/stop, the first of which is my web request to apache which then spawns off a cli php- but no breakpoints are hit.  If I enable multiple connections, the breakpoints get hit, but any web requests which may be going on spawn off a bunch of other debug tabs.  With xdebug output enabled I still only see this:
Session Initialized: default
Session Terminated: default
Session Initialized: default
Session Terminated: default

**Comment by msitarzewski** [comment]
Not sure if it's related, but I found that I had to quit Atom and relaunch to get debugging to work consistently. Then I changed from port 9000 to 8881 and I haven't had the problem since. It was related to committing code to GitHub (Shift Command A, then P). Can't imagine why that was, but changing the port fixed it.

**Comment by ciscon** [comment]
As of now my main problem seems to be that it doesn't listen to the "Continue to listen for debug sessions..." option, so merely closing the pane doesn't work to stop it listening so I'm forced to just close it out to stop it from catching things when I want to let php just run through without hitting all of the breakpoints I've set.

**Comment by jvlobo** [comment]
Any news on all the issues coming from last update?

Cheers!

**Comment by SleepWalker** [comment]
@cchamplin sorry, I'm use PHP debugger really rare, because I'm frontend developer :)

I have currently tested with disabled "Allow multiple debug sessions at once" and it seems to be ok. I can't reproduce the behaviour I have written before. With and without protocol debug option.
